### ISSUE TITLE
Free pulls campaign is missing

### ISSUE THREAD

**Issue by Wazhai** [trunghieumickey/priconne-en-event-timer#13]
On kenofnz version:
![Screenshot_20221204-101532_Firefox](https://user-images.githubusercontent.com/14195241/205483060-5baa3790-cb75-4d90-a9f9-92d435ee4e89.png)

**Comment by trunghieumickey** [comment]
It is intended because it not one of information that I found useful (Like Updated furniture). However, if everyone else feel it necessity to have then I will put that in just fine.

**Comment by trunghieumickey** [comment]
I think it quite late to put that in because events are almost end already, I'll put that in next time

**Comment by trunghieumickey** [comment]
Also, to not make them blended in with Focus Gacha, is it fine if I make a separated Category for that?

**Comment by Wazhai** [comment]
I think free pull campaign is **essential** information. There's constantly questions on Discord about when free pulls start or end. Please add it back. You can decide which category yourself.

Also the free pull campaign is still ongoing, and the current free pulls even have an unusual end time because it ends with the Nyaru banner, not on next daily reset.

**Comment by trunghieumickey** [comment]
Added on commit https://github.com/trunghieumickey/priconne-en-event-timer/commit/55c1334ed06b5a358df3527bf9f548f42bfd4e3c
