### ISSUE TITLE
⚠ Don't leak people's personal emails when they fill out the Feedback Form

### ISSUE THREAD

**Issue by Wazhai** [trunghieumickey/priconne-en-event-timer#8]
Title. Please delete any public Github issues containing emails and address this very problematic bot behaviour ASAP.

That said, thanks for your work on updating the timer site :)

**Comment by trunghieumickey** [comment]
Sorry about that, I'll hide your email right now

**Comment by Wazhai** [comment]
Not my email. It's visible in github edit history. You should just remake the issues manually.

**Comment by trunghieumickey** [comment]
Ok, it'll take some time to redone through

**Comment by trunghieumickey** [comment]
All redone, do you mind if I'm closing this issue ?

**Comment by Wazhai** [comment]
All good, just be more mindful when handling personal data in the future. Thanks for your work!
